Quote(s) -> pluralized properly
Manechat/izzy-moonbot pull request #531
Opened 2023-11-18 23:48 UTC by MrOnosa

It's a pet-peeve of mine.

2023-11-18 23:55 UTC, MrOnosa commented
That's what I get for trying to program on my cell phone.

2023-11-19 00:23 UTC, Ixrec commented
For what it's worth, if we want to be fancy about plural handling, what we'd really want is a little helper method like `pluralize(number, "thing", "things")`. It may be a trivial method, but over all the "(s)"s in a codebase like this (or in the one at my day job which does have such a helper) having a standard name for it and slightly less logic at the string interpolation site adds up to a significant benefit.

2023-11-19 00:50 UTC, MrOnosa commented
And that's what I get for not just forking the project because it was working locally but I forgot to update all the files using the GitHub editor.

Noted on using pluralize. Were you thinking of a full library, like [Pluralize.NET](https://github.com/sarathkcm/Pluralize.NET), or just a simple helper method?

2023-11-19 00:54 UTC, Ixrec commented
Oh I just meant a simple helper method for us. I don't think Izzy's usage of plural words is nearly advanced or dynamic enough to benefit from what Pluralize.NET is doing.

2023-11-19 00:56 UTC, Ixrec requested changes
just a few more small fixes

2023-11-19 00:56 UTC, Ixrec commented on Izzy-MoonbotTests/Tests/QuoteModuleTests.cs
> +    public async Task QuotesCommand_Tests()
Test name should mention the whole plural thing it's trying to test

2023-11-19 00:56 UTC, Ixrec commented on Izzy-MoonbotTests/Tests/QuoteModuleTests.cs
> +        // only one quote so that the "random" selection is deterministic for now
this comment is incorrect in this test

2023-11-19 14:36 UTC, Ixrec approved these changes

2023-11-19 14:36 UTC, merged

2023-11-21 02:12 UTC, ParaSwarm commented
@MrOnosa you're a peach and a warrior of light